# Generated by Django 5.2.8 on 2026-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['title'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('stay', 'Stay/Hotel'), ('activities', 'Activities & Sightseeing'), ('meals', 'Meals & Dining'), ('other', 'Other')], default='activities', max_length=50),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('stay', 'Stay/Hotel'), ('activities', 'Activities & Sightseeing'), ('meals', 'Meals & Dining'), ('other', 'Other')], max_length=50),
        ),
    ]
